# Dependencies
markdown:         kramdown
highlighter:      pygments

kramdown:
  input: GFM

# Permalinks
permalink: pretty

# Setup
title:            Grant Chau
tagline:          'Home'
description:      'Currently <a href="https://www.broadinstitute.org/stanley-center-psychiatric-research/genetics" target="_blank">@Broad</a>'
url:              https://github.com/gnchau     
baseurl:          /

author:
  name:           'Grant Chau'
gems: [jekyll-paginate, jekyll-gist]
plugins: [jekyll-paginate]
paginate:         5
paginate_path:  "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://gnchau.github.io/

# collections:
#   pages:
#     output: true
