# Dependencies
markdown:         kramdown
highlighter:      pygments

kramdown:
  input: GFM

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
domain:           gnchau.github.io
url:              http://gnchau.github.io
baseurl:          /gnchau.github.io

author:
  name:           'gnchau'
gems: [jekyll-paginate, jekyll-gist]
plugins: [jekyll-paginate]
paginate:         5
paginate_path:  "page:num"

# Custom vars
version:          2.1.0
